#!/usr/bin/env python3

import wpilib
from wpilib import RobotDrive

class MyRobot(wpilib.IterativeRobot):

    frontLeftChannel  = 2
    rearLeftChannel   = 3
    frontRightChannel = 1
    rearRightChannel  = 0


    joystickChannel   = 0

    def robotInit(self):
        '''Robot initialization function'''
        self.stick = wpilib.Joystick(self.joystickChannel)


        self.robotDrive = wpilib.RobotDrive(self.frontLeftChannel,
                                           self.rearLeftChannel,
                                           self.frontRightChannel,
                                           self.rearRightChannel)
        self.robotDrive.setExpiration(0.1)

        self.robotDrive.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, True)

        self.robotDrive.setInvertedMotor(RobotDrive.MotorType.kRearLeft, True)

    def teleopPeriodic(self):


        self.robotDrive.mecanumDrive_Cartesian(self.stick.getX(),
                                                   self.stick.getY(),
                                                   self.stick.getRawAxis(4), 0)


if __name__ == '__main__':
    wpilib.run(MyRobot)


